/**
 * pod-worker.js  --  the `pod` Worker behind pod.stluker.com
 *
 * Three routes, nothing else:
 *   GET /feed.xml        podcast RSS, built from PODCAST_KV at request time
 *   GET /audio/:id.mp3   the episode MP3, streamed from R2 (Range-aware)
 *   GET /                a plain landing page with the subscribe URL
 *
 * Same KV-at-request-time pattern as status/space/earth. Because /feed.xml is
 * generated by Worker code and there is no static file of that name, this does
 * NOT need run_worker_first -- but the wrangler.jsonc sets it anyway, because
 * the Jul 13-14 status incident was exactly a static asset silently shadowing
 * a Worker route, and being explicit costs nothing.
 *
 * Range support is not optional: Apple Podcasts and Overcast issue Range
 * requests on download. A 200-only handler makes episodes fail to scrub.
 */

const SHOW = {
  title: 'Earth and Orbit',
  subtitle: 'A five-minute daily briefing on space and earth science.',
  description:
    'Every morning, a short and honest look at what happened in space and on ' +
    'this planet - the launches, the discoveries, the storms and the science. ' +
    'Written and narrated automatically, five to seven minutes, no clickbait. ' +
    'Part of the stluker.com network.',
  author: 'Paul Luker',
  email: 'pdluker@gmail.com',
  language: 'en-us',
  category: 'Science',
  subcategory: 'Astronomy',
  explicit: 'false',
  siteUrl: 'https://pod.stluker.com',
  imageUrl: 'https://pod.stluker.com/cover.jpg',
};

function xmlEscape(s) {
  return String(s || '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}

function hhmmss(seconds) {
  const s = Math.max(0, Math.round(seconds || 0));
  const h = Math.floor(s / 3600);
  const m = Math.floor((s % 3600) / 60);
  const sec = s % 60;
  const pad = (n) => String(n).padStart(2, '0');
  return h > 0 ? `${h}:${pad(m)}:${pad(sec)}` : `${m}:${pad(sec)}`;
}

function buildFeed(episodes) {
  // Channel-level cover: this is what most podcast apps actually render as
  // "the show" (library grid, app icon, now-playing screen) -- the per-item
  // <itunes:image> below only surfaces in an episode list, which many apps
  // don't even bother showing. Use today's/latest generated art here so the
  // cover people actually see changes daily; fall back to the static
  // cover.jpg only on a day generateCoverImage failed and imageKey is null.
  const latest = episodes[0];
  const channelImageUrl = latest && latest.imageKey
    ? `${SHOW.siteUrl}/${latest.imageKey}`
    : SHOW.imageUrl;

  const items = episodes.map((ep) => {
    const audioUrl = `${SHOW.siteUrl}/audio/${ep.id}.mp3`;
    // Per-episode art if generateCoverImage succeeded that day; otherwise no
    // <itunes:image> element at all, and podcast apps fall back to the
    // channel-level image (SHOW.imageUrl / cover.jpg) automatically -- that's
    // the built-in RSS behavior, not something this code needs to implement.
    const imageTag = ep.imageKey
      ? `\n      <itunes:image href="${SHOW.siteUrl}/${xmlEscape(ep.imageKey)}"/>`
      : '';
    return `    <item>
      <title>${xmlEscape(ep.title)}</title>
      <description>${xmlEscape(ep.blurb || SHOW.subtitle)}</description>
      <itunes:summary>${xmlEscape(ep.blurb || SHOW.subtitle)}</itunes:summary>
      <pubDate>${xmlEscape(ep.pubDate)}</pubDate>
      <guid isPermaLink="false">stluker-pod-${xmlEscape(ep.id)}</guid>
      <link>${audioUrl}</link>
      <enclosure url="${audioUrl}" length="${ep.bytes || 0}" type="audio/mpeg"/>
      <itunes:duration>${hhmmss(ep.durationSeconds)}</itunes:duration>
      <itunes:episodeType>full</itunes:episodeType>
      <itunes:explicit>false</itunes:explicit>${imageTag}
    </item>`;
  }).join('\n');

  return `<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0"
     xmlns:itunes="http://www.itunes.com/dtds/podcast-1.0.dtd"
     xmlns:content="http://purl.org/rss/1.0/modules/content/"
     xmlns:atom="http://www.w3.org/2005/Atom">
  <channel>
    <title>${xmlEscape(SHOW.title)}</title>
    <link>${SHOW.siteUrl}</link>
    <atom:link href="${SHOW.siteUrl}/feed.xml" rel="self" type="application/rss+xml"/>
    <language>${SHOW.language}</language>
    <description>${xmlEscape(SHOW.description)}</description>
    <itunes:author>${xmlEscape(SHOW.author)}</itunes:author>
    <itunes:summary>${xmlEscape(SHOW.description)}</itunes:summary>
    <itunes:subtitle>${xmlEscape(SHOW.subtitle)}</itunes:subtitle>
    <itunes:type>episodic</itunes:type>
    <itunes:explicit>${SHOW.explicit}</itunes:explicit>
    <itunes:image href="${xmlEscape(channelImageUrl)}"/>
    <itunes:owner>
      <itunes:name>${xmlEscape(SHOW.author)}</itunes:name>
      <itunes:email>${xmlEscape(SHOW.email)}</itunes:email>
    </itunes:owner>
    <itunes:category text="${SHOW.category}">
      <itunes:category text="${SHOW.subcategory}"/>
    </itunes:category>
${items}
  </channel>
</rss>`;
}

/** Parse a single-range "bytes=start-end" header. Returns null if absent/odd. */
function parseRange(header, size) {
  if (!header) return null;
  const m = /^bytes=(\d*)-(\d*)$/.exec(header.trim());
  if (!m) return null;
  const [, rawStart, rawEnd] = m;
  if (rawStart === '' && rawEnd === '') return null;
  if (rawStart === '') {
    const len = Math.min(Number(rawEnd), size);
    return { offset: size - len, length: len };
  }
  const start = Number(rawStart);
  const end = rawEnd === '' ? size - 1 : Math.min(Number(rawEnd), size - 1);
  if (start > end || start >= size) return null;
  return { offset: start, length: end - start + 1 };
}

export default {
  async fetch(request, env) {
    const url = new URL(request.url);
    const path = url.pathname;

    // ---------------------------------------------------------- RSS feed
    if (path === '/feed.xml' || path === '/rss' || path === '/feed') {
      let manifest = [];
      try {
        const raw = await env.PODCAST_KV.get('podcast:manifest');
        if (raw) manifest = JSON.parse(raw);
      } catch { manifest = []; }

      return new Response(buildFeed(manifest), {
        headers: {
          'content-type': 'application/rss+xml; charset=utf-8',
          // Short TTL: a new episode should show up on the next poll, not in an
          // hour. Podcast apps poll on their own schedule anyway.
          'cache-control': 'public, max-age=300',
          'access-control-allow-origin': '*',
        },
      });
    }

    // ------------------------------------------------------- audio from R2
    if (path.startsWith('/audio/')) {
      const id = path.slice('/audio/'.length).replace(/\.mp3$/i, '');
      if (!/^\d{4}-\d{2}-\d{2}$/.test(id)) {
        return new Response('Not found', { status: 404 });
      }
      const key = `episodes/${id}.mp3`;

      const head = await env.POD_BUCKET.head(key);
      if (!head) return new Response('Not found', { status: 404 });

      const range = parseRange(request.headers.get('range'), head.size);
      const obj = await env.POD_BUCKET.get(key, range ? { range } : undefined);
      if (!obj) return new Response('Not found', { status: 404 });

      const headers = new Headers({
        'content-type': 'audio/mpeg',
        'accept-ranges': 'bytes',
        // NOT immutable: this URL's content CAN change if an episode is
        // regenerated at the same date (confirmed Jul 30 -- forced re-runs
        // during testing left stale cached artwork permanently stuck in a
        // podcast app because `immutable` told it never to re-check). A day
        // of caching plus ETag revalidation gets nearly all the same
        // performance benefit for the real one-per-day case while still
        // self-healing if content at this URL ever legitimately changes.
        'cache-control': 'public, max-age=86400, must-revalidate',
        etag: obj.httpEtag,
      });

      if (range) {
        const end = range.offset + range.length - 1;
        headers.set('content-range', `bytes ${range.offset}-${end}/${head.size}`);
        headers.set('content-length', String(range.length));
        return new Response(obj.body, { status: 206, headers });
      }
      headers.set('content-length', String(head.size));
      return new Response(obj.body, { status: 200, headers });
    }

    // ---------------------------------------------- per-episode cover art
    // Key format must match podcast-ingest.js's imageKey exactly:
    // `episodes/${day}.jpg`. buildFeed() references this same path directly
    // as `${SHOW.siteUrl}/${ep.imageKey}` -- not through a helper -- so if
    // this route's path prefix ever changes, that reference needs updating
    // too, or itunes:image links will 404 in every podcast app at once.
    if (path.startsWith('/episodes/') && path.endsWith('.jpg')) {
      const id = path.slice('/episodes/'.length).replace(/\.jpg$/i, '');
      if (!/^\d{4}-\d{2}-\d{2}$/.test(id)) {
        return new Response('Not found', { status: 404 });
      }
      const key = `episodes/${id}.jpg`;
      const obj = await env.POD_BUCKET.get(key);
      // No fallback-to-cover.jpg redirect here on purpose: buildFeed() only
      // emits <itunes:image> when imageKey is non-null, so a podcast app
      // should never request this URL for a day that has no image. If this
      // 404s anyway, that's a real bug worth seeing as a 404, not silently
      // serving the wrong day's art.
      if (!obj) return new Response('Not found', { status: 404 });

      return new Response(obj.body, {
        status: 200,
        headers: {
          'content-type': 'image/jpeg',
          // NOT immutable -- see the identical note on the /audio/ route
          // above. This exact bug (Jul 30): a forced re-run regenerated
          // today's cover art at the same URL, but the first fetch had
          // already told every downstream cache to treat it as permanent,
          // so the new art never propagated to anything that saw the old one
          // first.
          'cache-control': 'public, max-age=86400, must-revalidate',
          etag: obj.httpEtag,
        },
      });
    }

    // -------------------------------------------------- transcript (bonus)
    if (path.startsWith('/transcript/')) {
      const id = path.slice('/transcript/'.length).replace(/\.txt$/i, '');
      if (!/^\d{4}-\d{2}-\d{2}$/.test(id)) return new Response('Not found', { status: 404 });
      const raw = await env.PODCAST_KV.get(`podcast:episode:${id}`);
      if (!raw) return new Response('Not found', { status: 404 });
      const ep = JSON.parse(raw);
      return new Response(ep.script || '', {
        headers: { 'content-type': 'text/plain; charset=utf-8', 'cache-control': 'public, max-age=3600' },
      });
    }

    // ------------------------------------------------------- landing page
    if (path === '/' || path === '/index.html') {
      let manifest = [];
      try {
        const raw = await env.PODCAST_KV.get('podcast:manifest');
        manifest = raw ? JSON.parse(raw) : [];
      } catch { manifest = []; }
      const latest = manifest[0] || null;
      const archive = manifest.slice(1);

      // Shared by the latest card and every archive row -- server-rendered,
      // no client JS needed for layout, but the toggle itself needs a tiny
      // bit of JS since the transcript text isn't fetched until asked for
      // (a full day's transcript inlined into every row up front would bloat
      // the page for no reason -- most visitors will read zero of them).
      const transcriptToggle = (id) => `
  <button type="button" class="ttoggle" data-id="${xmlEscape(id)}" onclick="toggleTranscript(this)">Show full transcript</button>
  <div class="tbox" id="transcript-${xmlEscape(id)}" style="display:none"></div>`;

      const metaLine = (ep) => {
        const mins = Math.max(1, Math.round((ep.durationSeconds || 0) / 60));
        const dateStr = new Date(`${ep.id}T12:00:00Z`).toLocaleDateString('en-US', {
          month: 'long', day: 'numeric', year: 'numeric', timeZone: 'UTC',
        });
        const epNum = ep.episodeNumber ? `Episode ${ep.episodeNumber} - ` : '';
        return `${epNum}${dateStr} - ~${mins} min`;
      };

      const archiveHtml = archive.length ? `
<div class="card">
  <strong>Past episodes</strong>
  ${archive.map((ep) => `
  <div class="archive-row">
    ${ep.imageKey ? `<img src="/${xmlEscape(ep.imageKey)}" alt="" class="archive-thumb">` : '<div class="archive-thumb archive-thumb-empty"></div>'}
    <div class="archive-meta">
      <div class="archive-title">${xmlEscape(ep.title)}</div>
      <div class="archive-sub">${xmlEscape(metaLine(ep))}</div>
      <audio controls preload="none" src="/audio/${xmlEscape(ep.id)}.mp3" class="archive-audio"></audio>
      ${transcriptToggle(ep.id)}
    </div>
  </div>`).join('\n')}
</div>` : '';

      const html = `<!doctype html>
<html lang="en"><head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Earth and Orbit</title>
<style>
:root{color-scheme:dark}
body{margin:0;min-height:100vh;display:grid;place-items:center;
  background:radial-gradient(120% 100% at 50% 0%,#16213e 0%,#0a0e1a 60%);
  color:#e8ecf5;font:16px/1.6 ui-sans-serif,system-ui,-apple-system,sans-serif;padding:2rem}
main{max-width:34rem;width:100%}
h1{font-size:2.2rem;letter-spacing:-.02em;margin:0 0 .3rem}
p.sub{color:#8fa3c8;margin:0 0 2rem}
.card{background:rgba(255,255,255,.05);border:1px solid rgba(255,255,255,.1);
  border-radius:14px;padding:1.25rem;margin-bottom:1rem;backdrop-filter:blur(8px)}
code{background:rgba(0,0,0,.35);padding:.35rem .5rem;border-radius:6px;
  font-size:.85rem;word-break:break-all;display:block;margin-top:.5rem}
audio{width:100%;margin-top:.75rem}
a{color:#7ab8ff}
.ttoggle{margin-top:.6rem;background:rgba(255,255,255,.1);border:1px solid rgba(255,255,255,.2);
  color:#e8ecf5;border-radius:999px;padding:.4rem .9rem;font-size:.85rem;cursor:pointer}
.ttoggle:hover{background:rgba(255,255,255,.16)}
.tbox{margin-top:.75rem;white-space:pre-wrap;color:#c3ccdb;font-size:.9rem;line-height:1.6;
  border-top:1px solid rgba(255,255,255,.1);padding-top:.75rem}
.archive-row{display:flex;gap:.85rem;padding:.85rem 0;border-top:1px solid rgba(255,255,255,.08)}
.archive-row:first-of-type{border-top:none;padding-top:.5rem}
.archive-thumb{width:64px;height:64px;border-radius:8px;object-fit:cover;flex-shrink:0}
.archive-thumb-empty{background:rgba(255,255,255,.06)}
.archive-meta{flex:1;min-width:0}
.archive-title{font-weight:600;font-size:.95rem}
.archive-sub{color:#8fa3c8;font-size:.8rem;margin-top:.15rem}
.archive-audio{height:32px;margin-top:.5rem}
</style></head><body><main>
<h1>Earth and Orbit</h1>
<p class="sub">${xmlEscape(SHOW.subtitle)}</p>
<div class="card">
  <strong>Subscribe</strong>
  <p style="margin:.5rem 0 0;color:#8fa3c8">Paste this into Apple Podcasts, Overcast, or Pocket Casts:</p>
  <code>${SHOW.siteUrl}/feed.xml</code>
</div>
${latest ? `<div class="card">
  ${latest.imageKey ? `<img src="/${xmlEscape(latest.imageKey)}" alt="" style="width:100%;border-radius:10px;margin-bottom:.75rem;display:block">` : ''}
  <strong>${xmlEscape(latest.title)}</strong>
  <p style="margin:.3rem 0 0;color:#8fa3c8;font-size:.85rem">${xmlEscape(metaLine(latest))}</p>
  <p style="margin:.5rem 0 0;color:#8fa3c8">${xmlEscape(latest.blurb || '')}</p>
  <audio controls preload="none" src="/audio/${xmlEscape(latest.id)}.mp3"></audio>
  ${transcriptToggle(latest.id)}
</div>` : `<div class="card"><strong>No episodes yet.</strong>
  <p style="margin:.5rem 0 0;color:#8fa3c8">The first briefing lands after the next daily run.</p></div>`}
${archiveHtml}
<p style="color:#5f7194;font-size:.85rem">Part of the
  <a href="https://stluker.com">stluker.com</a> network - see also
  <a href="https://space.stluker.com">space</a> and
  <a href="https://earth.stluker.com">earth</a>.</p>
</main>
<script>
// Transcripts are fetched on first click, not inlined at page load -- most
// visitors read zero of them, so loading every episode's full script
// up front would be pure waste. Cached in the DOM after the first fetch,
// so repeated toggles on the same episode don't re-fetch.
function toggleTranscript(btn) {
  var id = btn.getAttribute('data-id');
  var box = document.getElementById('transcript-' + id);
  if (box.dataset.loaded === '1') {
    var showing = box.style.display !== 'none';
    box.style.display = showing ? 'none' : 'block';
    btn.textContent = showing ? 'Show full transcript' : 'Hide transcript';
    return;
  }
  btn.textContent = 'Loading...';
  fetch('/transcript/' + id + '.txt')
    .then(function (r) { if (!r.ok) throw new Error('not found'); return r.text(); })
    .then(function (text) {
      box.textContent = text;   // textContent, not innerHTML -- safe by
                                 // construction, no manual escaping needed
      box.dataset.loaded = '1';
      box.style.display = 'block';
      btn.textContent = 'Hide transcript';
    })
    .catch(function () { btn.textContent = 'Could not load transcript'; });
}
</script>
</body></html>`;

      return new Response(html, {
        headers: { 'content-type': 'text/html; charset=utf-8', 'cache-control': 'public, max-age=300' },
      });
    }

    // Anything else falls through to static assets (cover.jpg etc).
    return env.ASSETS ? env.ASSETS.fetch(request) : new Response('Not found', { status: 404 });
  },
};
